// generated by atlas.exe
string getWorldOffenderVisualCommand(string transportName, int colorFactionId, int id) {
	string command = "";
	// input parameters: $transport_name, $color_faction_id, $id
	string markerRect = '0.903339 0.742068 0.954722 0.79675';
	string markerSize = '128 128';
	dictionary positions = {
		{'map2_to_map8', '288.552 512.376'},
		{'map8_to_map2', '286.749 513.322'},
		{'map2_to_map4', '369.11 354.162'}, 
		{'map4_to_map2', '369.11 354.162'},       
		{'map3_to_map4', '627.92 311.172'},
		{'map4_to_map3', '627.92 311.172'},
		{'map3_to_map1', '634.864 418.301'},
		{'map1_to_map3', '633.973 419.432'},
		{'map1_to_map8', '406.561 520.953'},
		{'map8_to_map1', '407.601 519.202'},
		{'map6_to_map1', '481.494 532.357'},
		{'map1_to_map6', '480.065 532.185'},
		{'map3_to_map7', '688.305 498.838'},
		{'map7_to_map3', '689.152 497.674'},
		{'map6_to_map5', '364.244 694.697'},
		{'map5_to_map6', '364.891 695.912'},
		{'map6_to_map8', '399.456 608.444'},
		{'map8_to_map6', '399.646 609.871'},
		{'map6_to_map9', '645.546 634.851'},
		{'map9_to_map6', '645.641 635.521'},
		{'map9_to_map3', '768.96 590.22'},
		{'map3_to_map9', '753.48 493.2'},
		{'map10_to_map5', '379.825 768.435'},
		{'map5_to_map10', '379.314 769.713'},
		{'map9_to_map10', '667.075 753.471'},
		{'map10_to_map9', '667.722 754.686'}
	};
	dictionary rotations = {
		{'map2_to_map8', '3.54365'},
		{'map8_to_map2', '0.415673'},
		{'map2_to_map4', '-0.744738'}, 
		{'map4_to_map2', '2.39686'},     
		{'map3_to_map4', '0.761315'},
		{'map4_to_map3', '3.93727'},
		{'map3_to_map1', '1.53521'},
		{'map1_to_map3', '-1.63686'},
		{'map1_to_map8', '2.52022'},
		{'map8_to_map1', '-0.661941'},
		{'map6_to_map1', '-0.112294'},
		{'map1_to_map6', '3.00941'},
		{'map3_to_map7', '2.4995'},
		{'map7_to_map3', '-0.627508'},
		{'map6_to_map5', '2.29903'},
		{'map5_to_map6', '-0.850112'},
		{'map6_to_map8', '1.71095'},
		{'map8_to_map6', '-1.45054'},
		{'map6_to_map9', '-1.76974'},
		{'map9_to_map6', '1.36756'},
		{'map9_to_map3', '0.168825'},
		{'map3_to_map9', '3.30935'},
		{'map10_to_map5', '1.42862'},
		{'map5_to_map10', '-1.72052'},
		{'map9_to_map10', '2.29903'},
		{'map10_to_map9', '-0.850112'}
	};
	string c = '';
	if (positions.exists(transportName)) {
		string p;
		string r;
		positions.get(transportName, p);
		rotations.get(transportName, r);
		c = "<visual id='" + id + "' layer='1' position='" + p + "' size='" + markerSize + "' texture_rect='" + markerRect + "' rotation='" + r + "' color_faction='" + colorFactionId + "' />";
	}
	if (c != "") {
		command = "<command class='set_world_situation'>\n";
		command += c;
		command += "</command>";
	}
	return command;
}
