// generated by atlas.exe
string getWorldInitCommand() {
	string command = """
<command class='set_world_situation'>
	<faction id='0' name='Green' color='0.1 0.5 0' />
	<faction id='1' name='Grey' color='0.5 0.5 0.5' />
	<faction id='2' name='Brown' color='0.5 0.25 0' />
	<region id='0' name='map1' position='501.794 414.398' size='280.01 244.85' texture_rect='0.206162 0.569839 0.335796 0.683196'>
	</region>
	<region id='1' name='map2' position='265.534 415.328' size='266.566 248.404' texture_rect='0.0265609 0.569447 0.149971 0.684449'>
	</region>
	<region id='2' name='map3' position='737.701 386.864' size='240.018 249.571' texture_rect='0.419969 0.555999 0.531088 0.671541'>
	</region>
	<region id='3' name='map4' position='475.283 241.515' size='348.876 243.276' texture_rect='0.177947 0.433499 0.339463 0.546126'>
	</region>
	<region id='4' name='map5' position='272.25 746.89' size='250.343 191.059' texture_rect='0.0334253 0.898889 0.149325 0.987342'>
	</region>
	<region id='5' name='map6' position='522.46 610.296' size='270.532 205.292' texture_rect='0.217923 0.713023 0.343169 0.808066'>
	</region>
	<region id='6' name='map7' position='698.893 545.681' size='212.553 132.547' texture_rect='0.408359 0.699948 0.506763 0.761312'>
	</region>
	<region id='7' name='map8' position='304.545 583.855' size='262.178 173.311' texture_rect='0.0456369 0.708185 0.167016 0.788421'>
	</region>
	<region id='8' name='map9' position='752.793 657.813' size='235.254 355.023' texture_rect='0.428058 0.819695 0.536972 0.984058'>
	</region>
	<region id='9' name='map10' position='521.392 740.455' size='329.446 191.823' texture_rect='0.203791 0.895733 0.356312 0.98454'>
	</region>
	<region id='10' name='map11' position='243.165 227.599' size='109.583 107.539' texture_rect='0.0525433 0.458477 0.103276 0.508263'>
	</region>
	<region id='11' name='map12' position='728.931 194.963' size='109.583 107.539' texture_rect='0.446101 0.443368 0.496834 0.493154'>
	</region>
	<visual id='0' layer='0' comment='#rect12877' position='499.817 484.299' size='932.781 908.343' texture_rect='0.0154755 0.0139478 0.447318 0.434477'>
	</visual>
	<visual id='1' layer='1' comment='#rect12877' position='511.759 490.408' size='979.62 965.364' texture_rect='0.544162 0.00357697 0.997689 0.450505'>
	</visual>
</command>
	""";
	return command;
}
